# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0ced3b12a6c3d348781124cd48f182b705a0db83f221e9737648cf11c1109ba849bc55a9cace2310c16a4916a7e21805bcb62f2ccbda992c47b178bc75637fd

test:
  secret_key_base: 257208c3d8a7aafe7707d321a6d32d7a3c63900c6168192e62b22fdc68b05d695cf87e4f0c18210b9f94a20f4baffb7eb85a5b5bf92ddfd84fe09c243c2839dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
